### ISSUE TITLE
Knorke Youtube Feeds

### ISSUE THREAD

**Issue by tomjn** [tomjn/springinfo#2]
2 youtube playlists are to be added, and the main knorke feed to be removed

Need to:
- Find the playlists
- Figure out what the RSS feeds for them would be
- Add them to site

**Comment by tomjn** [comment]
Related to #3

**Comment by knorker** [comment]
find the playlists:
http://springrts.com/phpbb/viewtopic.php?f=1&t=27734&p=526000&hilit=playlists#p526000

Figure out what the RSS feeds for them would be:
http://springrts.com/phpbb/viewtopic.php?f=1&t=27734&hilit=playlists&start=80#p544888
or
http://elliottbledsoe.com/brain-drain/how-to/rss-subscribe-to-youtube-playlist/

Add them to site:
....

**Comment by knorker** [comment]
bump?

**Comment by tomjn** [comment]
The Zero-K feed has been added

The other feed is not yet added

For reference so I don't have another hoop to jump through, here's the feeds:

> so i made two new playlists into which new stuff will go:
> http://www.youtube.com/playlist?list=PL81F8751D716422BE
> zero-k
> 
> http://www.youtube.com/playlist?list=PL45972DFEBA7D69E9
> other spring

**Comment by tomjn** [comment]
As a sidenote, the 'other spring' playlist is incomplete, and I'm unsure how to categorise it

**Comment by knorker** [comment]
How is the 'other spring' playlist incomplete?
Most things on springinfo.info are in category "Uncategorized" (and some also in "Videos") so just put my lists into the same.

**Comment by knorker** [comment]
scam

**Comment by tomjn** [comment]
? Springinfo isn't even used, it's not worth stressing about a playlist with 4 videos from a decade ago, people use Discord for this stuff now
