### ISSUE TITLE
clicking a news should go to original source instead of copy

### ISSUE THREAD

**Issue by knorker** [tomjn/springinfo#5]
When clicking onto a news-thing on frontpage, the user should be directed to the source of the news.
At the moment springinfo.info opens with a copy of the content.
These copies usually have messed up formating etc and are out of content, for example on
http://www.springinfo.info/2014/09/zero-k-zk-1v1-tournament-september-20-2014/
it says:

"To sign up simply leave a post in the comments"
Of course it only makes sense to sign up via comments in the original thread.

**Comment by tomjn** [comment]
This is a bug, the new automation stores the origin URL slightly differently. I'm making adjustments to correct the issue

**Comment by tomjn** [comment]
Fixed
