### ISSUE TITLE
playlist of zK tourney videos should not be in news because spam

### ISSUE THREAD

**Issue by knorker** [tomjn/springinfo#6]
Every month there is a zK tourney. For each tourney dozen of videos get uploaded.
Having all those videos on the frontpage at once is bad.
![bla](https://cloud.githubusercontent.com/assets/3044855/4352728/97f9c2d2-4229-11e4-9fec-d817be166ce1.jpg)

zero-K already has announcements about tourneys (with links stream and videos of the replays being added as they are uploaded) so it is not nessecary to have these videos seperately and in fact counterproductive because the "real" tourney-post is lost.

**Comment by tomjn** [comment]
The videos aren't intended to announce a tourney. SpringInfo has a videos archive that catalogs the videos made about in and for spring.

Your actual problem is "X posted a lot of news in a short space of time, and pushed the next item off of the list". This can't be solved without moving away from a simplistic naive list, and your expectations for a list of 10 items ordered by date is unrealistic ( hint: they're not sorted by relevance )

Either way the answer is no, I am not removing the Zero-K tournament youtube channel.

**Comment by knorker** [comment]
QUOTE: Your actual problem is "X posted a lot of news in a short space of time, and pushed the next item off of the list".

Almost. The actual problem is that a feed where it is know that it will regularly post lots of news in a short space of time, should not be shown on the springrts.com frontpage.

For your own video archive do whatever you want, but this about the springrts.com frontpage where it is clearly not good to have this youtube included like this. Especially since the videos/tourneys are already covered by a better, less spammy way. (regular human-written news by zero-k people)

**Comment by tomjn** [comment]
This is SpringInfo.info, not springrts.com, and springrts.com pulls in the **_full**_ feed, there are other feeds, and ways of manipulating the feed URLs to be more selective. Perhaps this issue would be better posted on the spring website repository, or in the Mantis bug tracker.

I refuse to compromise the entire sites main RSS feed for this, you ask for an RSS feed of everything, you got an RSS feed for everything, now you're complaining you got everything.

**Comment by knorker** [comment]
QUOTE: "you ask for an RSS feed of everything"
I never asked for such a thing.

I only care about the news-box on springrts.com, and my issue how it is spammed.
If you are not the person willing/able/responsible to fix that, then I will see if someone else is, maybe on forum or mantis bugtracker as you said.
